### ISSUE TITLE
API documentがあれば便利

### ISSUE THREAD

**Issue by kota-shiokara** [TadaTeruki/RDGL#1]
すごく面白いですが、API documentがあるともっといいなと思いました。
下記の記事とか参考になるかも？
https://www.twihike.dev/docs/golang-primer/documentation

**Comment by kota-shiokara** [comment]
ありましたね...
https://pkg.go.dev/github.com/TadaTeruki/RDGL@v0.1.0

これをReadmeに入れるのと内容の充実があるとユーザー的には嬉しいのかもしれないです

**Comment by TadaTeruki** [comment]
提案ありがとうございます！
いつのまにこんなドキュメントができていたとは...Goすごいですね...
READMEにて追加させていただきます。
